// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riaogxzxnsnhmvfnrvjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpYW9neHp4bnNuaG12Zm5ydmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTY4MzAsImV4cCI6MjA2MDQ5MjgzMH0.EHMd1SFEq6dhsyusKpHCcCdPNsp8gz-qA8qtoXsNOLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);